### ISSUE TITLE
Formatting for custom data

### ISSUE THREAD

**Issue by Brandoncheaa** [gist-ailab/SleePyCo#10]
Previously you mentioned the highpass cutoff being at 100Hz and the lowpass being at 0.3Hz however when I run those values I get errors:

"Traceback (most recent call last):
  File "train_model.py", line 158, in <module>
    main()
  File "train_model.py", line 120, in main
    generated_data_filtered = apply_filter(generated_data_resampled, low_cutoff, high_cutoff, fs)
  File "/cluster/academic/projects/ASCS/env/GAN-Sleep/utils.py", line 219, in apply_filter
    b_high, a_high = butter_highpass(high_cutoff, fs, order=order)
  File "/cluster/academic/projects/ASCS/env/GAN-Sleep/utils.py", line 211, in butter_highpass
    raise ValueError(f"Invalid highpass filter cutoff frequency: {cutoff} Hz (normalized: {normal_cutoff})")
ValueError: Invalid highpass filter cutoff frequency: 100 Hz (normalized: 2.0)"

**Comment by Brandoncheaa** [comment]
I got data loaded in actually, however I am getting "[INFO] Model prepared, Device used: cuda GPU:0,1
Predicted:  tensor([0], device='cuda:0')" I was assuming i'd see a confusion matrix so i'm assuming I did something wrong.

**Comment by Brandoncheaa** [comment]
My concern seems to lie with the high-pass cutoff frequency being at 100 Hz it is beyond the Nyquist frequency for a sampling rate of 100 Hz, making the normalized frequency greater than 1 which I think it causing my error.

**Comment by SeongjuLee** [comment]
I also agree with that the reason why you get error is due to Nyquist frequency. If you have signals with sampled larger than 200 Hz, preprocess your signal with the following process: applying high-pass and low-pass filter -> resample with 100 Hz
If the sampling rate of signal you have is smaller than 200 Hz, apply 30 Hz filter as preprocessed in Sleep-EDF dataset.

**Comment by Brandoncheaa** [comment]
Do you know why I may be getting this error? 
"File "/cluster/research-groups/ramasubramanian/workspace/cheab/miniconda/envs/sleepyco/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/cluster/academic/projects/ASCS/env/SleePyCo/models/classifiers.py", line 168, in forward
    pe = self.pe[hop//2::hop, :]
ValueError: slice step cannot be zero"

**Comment by Brandoncheaa** [comment]
I have taken a more simple approach, generating data not using GAN. Here is my dataset dimensions at (1,1,30000) sampled at 100Hz for 300s. I have provided the datset. The issue I have is similar to a previous user the Tensor[0], is the test_custom.py supposed to provide some sort of confusion matrix for how the custom data tests against the train data?
[eeg_data_reshaped.csv](https://github.com/gist-ailab/SleePyCo/files/15494098/eeg_data_reshaped.csv)

I even took a part of the sleep-edf-2013 dataset and cut them into batches with the same dimensions that are specified, however it is still showing tensor([0], device='cuda:0').

**Comment by SeongjuLee** [comment]
![Image](https://github.com/user-attachments/assets/cb389bf8-31f0-4009-b4c0-c6544ff62f78)
I tried to check the result by scaling the signal to have the similar scale with Sleep-EDF
I scale your signal x5 up (in amplitude) then I got label 1.
Can you check about the scale of the signal and the ground truth?
